# Generated by Django 2.2.6 on 2020-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('enterprise_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('weight_kpi', models.CharField(blank=True, max_length=1000, null=True)),
                ('variability_kpi', models.CharField(blank=True, max_length=1000, null=True)),
                ('n_of_occurences', models.CharField(blank=True, max_length=1000, null=True)),
                ('n_of_spread', models.CharField(blank=True, max_length=1000, null=True)),
                ('mux', models.CharField(blank=True, max_length=1000, null=True)),
                ('Max', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
